---
- name: kubeadm init
  become: yes
  shell: kubeadm init --apiserver-advertise-address 192.168.56.101

- name: create $HOME/.kube dir
  file: path={{ ansible_env.HOME }}/.kube state=directory

- name: cp kubeconfig
  become: yes
  shell: cp -i /etc/kubernetes/admin.conf {{ ansible_env.HOME }}/.kube/config

- name: chown kubeconfig
  shell: sudo chown $(id -u):$(id -g) {{ ansible_env.HOME }}/.kube/config

- name: apply network addon
  shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
